config/routes.rb
Rails.application.routes.draw do

  resources :subgenres
  resources :movies
  resources :genres

  get 'lookup/genres' => 'lookup#lookup_genres', as: :lookup_genres

  get '/debug' => 'developer_tools#debug'
  get '/sandbox' => 'developer_tools#sandbox'

  get 'pages/about'
  get 'pages/slide_batch' => 'pages#slide_batch'
  get 'admin/movies_index'

  root 'pages#home'
end

app/models/movie.rb
class Movie < ActiveRecord::Base
	has_and_belongs_to_many :genres
	validates :title, :photo, :year, :rating, :length, :summary, presence: true
	mount_uploader :photo, PhotoUploader
	# mount_uploaders :scenes, PhotoUploader

	def self.search(search)
		Movie.where('title ~* :search', search: "(#{search})")
	end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @genres = Genre.all
    @movies = Movie.search(params[:search])
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
    @genres = Genre.all
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to admin_movies_index_url, notice: 'Movie was successfully created' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to admin_movies_index_url, notice: 'Movie was successfully updated' }
        format.json { render :index, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to admin_movies_index_url, notice: 'Movie was successfully deleted' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
      @genres = Genre.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :photo, :photo_cache, :summary, :rating, :genre_id, genre_ids: [])
    end
end

app/helpers/movies_helper.rb
module MoviesHelper

  def carousel_data(movies, genre, array)
    movies.each do |movie|
      if movie.genre_ids.include?(genre.id)
        array.push(movie.id)
      end
    end
  end

  def carousel(array)
    i = 0
    index = 1
    @li_begin = "<li id='auto-width'>".html_safe
    @li_end = "</li>".html_safe
    @div_begin = "<div class='poster poster-#{index}'>".html_safe
    @div_end = "</div>".html_safe 
    while array[i]
      count = 0
      @li_begin
	      while count < 6
	        @movie = Movie.find_by(id: array[i])
	        if i < array.length - 1
	        	@div_begin
	        	  link_to image_tag(@movie.photo, class: "img-responsive"), movie_path(@movie)
	        	@div_end
	          i += 1
	          index += 1
	          count += 1
	        elsif i == array.length - 1
	          @div_begin
	            link_to image_tag(@movie.photo, class: "img-responsive"), movie_path(@movie)
	          @div_end
	          i += 1
	          break
	        end
	      end
      @li_end
    end
  end

end

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  
<div class="row">
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
</div>

<div class="row">
<div class="jumbotron-index col-sm-10 col-sm-offset-1">

  <div class="row">
    <div class="form-group col-sm-8 col-sm-offset-2">
      <%= f.label :title %><br>
      <%= f.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group col-sm-8 col-sm-offset-2">
      <%= f.label :genre_ids, "Add Genre" %><br>
      <%= f.collection_select :genre_ids, Genre.order(:name), :id, :name, {}, {class: "form-control genre-select", multiple: "multiple", autofocus: true} %>
    </div>

    <div class="form-group col-sm-8 col-sm-offset-2">
      <%= f.label :photo %>
      <%= f.file_field :photo, class: 'edit-photo' %>
      <%= f.hidden_field :photo_cache %>
    </div>

    <div class="image-preview col-sm-8 col-sm-offset-2">
      <% if @movie.photo? %> 
        <%= image_tag(@movie.photo_url, class: "img-responsive") %>
      <% else %>
        <img/> 
      <% end %>        
    </div>

    <div class="form-group col-sm-8 col-sm-offset-2">
      <%= f.label :summary %><br>
      <%= f.text_area :summary, class: "form-control", rows: 5 %>
    </div>

    <div class="form-group col-sm-8 col-sm-offset-2">
      <%= f.label :rating %><br>
      <%= f.text_field :rating, class: "form-control" %>
    </div>
  </div>

  <br>
  <div class="row actions text-center">
    <%= f.submit "Save", class: "btn btn-lg btn-primary" %>
  </div>
</div>
</div>
<% end %>

<script type="text/javascript">
  $(".genre-select").select2();
</script>

app/views/movies/edit.html.erb
<div class="container">
<div class="admin-row">
  <h1 class="text-center">Editing Movie</h1>
</div>

<%= render 'form' %>

<div class="row text-center">
  <%= link_to 'Show', @movie, class: "btn btn-lg btn-primary" %> |
  <%= link_to 'Back', admin_movies_index_path, class: "btn btn-lg btn-primary" %>
</div>
<br>
</div>

app/views/movies/index.html.erb
<% if @movies.blank? %>
  <br>
  <div class="search-row text-center">
    <h1>Title not found</h1>
  </div>
<% else %>
  <br>
  <div class="row">
    <div class="people col-xs-10 col-xs-offset-1 col-md-8 col-md-offset-1">

    </div>
  </div>
  <br>
  <div class="search-row">
    <div class="col-xs-12">
      <% @movies.each do |movie| %>
        <div class="poster">
          <%= link_to image_tag(movie.photo), movie_path(movie), class: "img-responsive" %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/movies/new.html.erb
<div class="container text-center">
  <div class="admin-row">
    <h1>New Movie</h1>
  </div>

  <%= render 'form' %>

  <div class="row text-center">
    <%= link_to 'Back', movies_path, class: "btn btn-lg btn-primary" %>
  </div>
</div>

app/views/movies/show.html.erb
<div class="container">
	<div class="admin-row show-movie">
		<div class="col-sm-8">
			<img class="img-responsive" src="<%= @movie.photo %>">
		</div>
		<div class="col-sm-8">
			<h2><%= @movie.title %></h2>
			<p><%= @movie.summary %></p>
			<span><%= @movie.year %></span>
			<span><%= @movie.rating %></span>
			<span><%= @movie.length %></span>
		</div>
	</div>
	<br>
	<br>
</div>