config/routes.rb
Rails.application.routes.draw do

  resources :subgenres
  resources :movies
  resources :genres

  get 'lookup/genres' => 'lookup#lookup_genres', as: :lookup_genres

  get '/debug' => 'developer_tools#debug'
  get '/sandbox' => 'developer_tools#sandbox'

  get 'pages/about'
  get 'pages/slide_batch' => 'pages#slide_batch'
  get 'admin/movies_index'

  root 'pages#home'
end

app/models/movie.rb
class Movie < ActiveRecord::Base
	has_and_belongs_to_many :genres
	validates :title, :photo, :year, :rating, :length, :summary, presence: true
	mount_uploader :photo, PhotoUploader
	# mount_uploaders :scenes, PhotoUploader

	def self.search(search)
		Movie.where('title ~* :search', search: "(#{search})")
	end
end

app/views/pages/_action_slider.html.erb
<div class="row">
  <div class="col-xs-12">
    <% @movies.each do |movie| %>
      <div class="poster">
        <%= image_tag(movie.photo, class: "img-responsive") %>
      </div>
    <% end %>
  </div>
</div>

<div class="slider-action">
  <span class="glyphicon glyphicon-menu-left slider-arrow">
    <p class="sr-only">Go to previous slide</p>
  </span>

  <span class="glyphicon glyphicon-menu-right slider-arrow">
    <p class="sr-only">Go to next slide</p>
  </span>

  <div id="slide-info">
    <img src="pirates-logo.png" class="img-responsive" id="movie-logo"/> 

    <div id="movie-content">
      <span id="year">2003</span>
      <span id="rating">PG-13</span>
      <span id="movie-length">2h 23min</span>

      <p id="blurb">
        A sword-handy blacksmith teams up with a clever yet eccentric outlaw to rescue his love from a crew of undead pirates.
      </p>
      
      <div id="slide-buttons">
        <a href="/movies/1" class="btn-blue" id="play"><i class="fa fa-play"></i>PLAY</a>
        <a href="#" class="btn-clear"><i class="fa fa-plus"></i>MY LIST</a>
      </div>
    </div>
  </div>
</div>

app/views/pages/_carousels.html.erb
<% @genres.each do |genre| %>
  <div class="row carousel-row">
    <h3>
      <a href=<%= genre_path(genre) %>>
        <%= genre.name %>
        <i class="fa fa-chevron-right"></i>
      </a>
    </h3>
    <div class="slider-<%= genre.name %>">
      <div class="border-left"></div>
      <div class="border-right"></div>
      <ul>
        <% genre.movie_ids.each_slice(@batch.to_i) do |batch| %>
          <li class="max-92">
            <% batch.each do |movie_id| %>
              <% @movie = genre.movies_hash[movie_id] %>
              <div class="poster">
                <div class="poster-inner">
                  <%= link_to image_tag(@movie.photo), movie_path(@movie) %>
                </div>
              </div>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/pages/_exp_carousel.html.erb
<% @genre = Genre.find_by(id: 1) %>
<div class="row">
  <div class="row">
    <h3>
      <a href=<%= genre_path(@genre) %> >Action & Adventure<i class="glyphicon glyphicon-chevron-right"></i></a>
    </h3>

    <ol></ol>
  </div>

  <div class="carousel">
    <div class="shadow-left">
      <a class="carousel-arrow previous">
        <i class="fa fa-angle-left"></i>
      </a>
    </div>
    <div class="shadow-right">
      <a class="carousel-arrow forward">
        <i class="fa fa-angle-right"></i>
      </a>
    </div>
    <ul>
      <% @movies.each do |movie| %>
        <% if movie.genre_ids.include?(@genre.id) %>
          <li>
            <div class="poster">
              <%= link_to image_tag(movie.photo, class: "img-responsive"), movie_path(movie) %>
            </div>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>

app/views/pages/_genre_posters.html.erb
<% @genres.each do |genre| %>
  <div class="row">
    <% if genre.name == "Action" %>
      <h3><a href=<%= genre_path(genre) %> >Action & Adventure<i class="fa fa-chevron-right"></i></a></h3>
      <!-- <h3>
        <%#= link_to "Action & Adventure"<i class="fa fa-chevron-right"></a>, genre_path(genre) %>
      </h3> -->
    <% else %>
      <h3><a href=<%= genre_path(genre) %> ><%= genre.name %><i class="fa fa-chevron-right"></i></a></h3>
    <% end %>
  </div>

	<% @movie_ids = genre.movie_ids %>
	  <% for i in @movie_ids %>
	    <% @movie = Movie.find_by(id: i) %>

		  <div class="poster">
        <div class="poster-inner">
          <%= link_to image_tag(@movie.photo, class: "img-responsive"), movie_path(@movie) %>
        </div>
		  </div>

		<% end %>
	<% end %>
<% end %>

app/views/pages/_posters.html.erb
<% i = 0 %>
<% arr = [] %>
<% movies = [] %>
<% movieIds = [] %>
<% for movie in @movies %>
  <% img = Magick::Image.ping("#{Rails.root}/public#{movie.photo}").first %>
  <% width = img.columns %>
  <% if width > 500 %>
    <% i += 2 %>
    <% arr.push(2) %>
    <% movies.push(movie.photo) %>
    <% movieIds.push(movie.id) %>
  <% else %>
    <% i += 1 %>
    <% arr.push(1) %>
    <% movies.push(movie.photo) %>
    <% movieIds.push(movie.id) %>
  <% end %>
  <% if i == 3 %>
    <div class="row">
    <% j = 0 %>
    <% for e in movies %>
      <% if arr[j] == 2 %>
        <div class="col-md-8">
          <div class="thumbnail">
            <%= link_to image_tag(e), movie_path(movieIds[j]) %>
          </div>
        </div>
      <% elsif arr[j] == 1 %>
        <div class="col-md-4">
          <div class="thumbnail">
            <%= link_to image_tag(e), movie_path(movieIds[j]) %>
          </div>
        </div>
      <% end %>
      <% j += 1 %>
    <% end %>
    </div>
    <% i = 0 %>
    <% arr = [] %>
    <% movies = [] %>
    <% movieIds = [] %>
  <% end %>
<% end %>

app/views/pages/about.html.erb
<div class="jumbotron">
  <div class="container">
    <div class="main">
      <h1>About Bolt</h1>
      <p>Buy or rent from the largest selection of movies and TV episodes. Try it for 30 days absolutely free. After your free trial, it's only $9.99/month for unlimited streaming, anywhere you go.</p>
    </div>
  </div>
</div>

app/views/pages/debug.html.erb
<div class="container">
	<div class="row">
		<h1 class="text-center">Debug All The Things!!!</h1>
	</div>

	<div class="row">
		<p><%= debug @genres %></p>
	</div>

	<div class="row">
		<p><%= @genres[1].movies_hash %></p>
	</div>

	<!-- <div class="row">
		<h2>Movies_Hash</h2>
		<p><%#= debug @movies_hash %></p>
	</div>

	<div class="row">
		<h2>Movies_Array</h2>
		<p><%#= debug @movies_array %></p>
	</div>

	<div class="row">
		<h2>Genres</h2>
		<p><%# debug @genres %></p>
		<p><%#= debug @movie_ids %></p>
	</div>

	<div class="row">
		<h2>Movies</h2>
		<p><%#= debug @movie.attributes %></p>
		<p><%#= debug @movies %></p>
	</div> -->
</div>

app/views/pages/home.html.erb
<div class="slider-frame">
  <span class="fa fa-angle-left slider-arrow slider-prev">
    <p class="sr-only">Go to previous slide</p>
  </span>

  <span class="fa fa-angle-right slider-arrow slider-next">
    <p class="sr-only">Go to next slide</p>
  </span>

  <div id="slide-info">
    <img src="pirates-logo.png" class="img-responsive" id="movie-logo"/> 

    <div id="movie-content">
      <span id="year">2003</span>
      <span id="rating">PG-13</span>
      <span id="movie-length">2h 23min</span>

      <p id="blurb">
        A sword-handy blacksmith teams up with a clever yet eccentric outlaw to rescue his love from a crew of undead pirates.
      </p>
      
      <div id="slide-buttons">
        <a href="/movies/1" class="btn-blue" id="play"><i class="fa fa-play"></i>PLAY</a>
        <a href="#" class="btn-clear"><i class="fa fa-plus"></i>MY LIST</a>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="supporting col-xs-12">
      <h2>A world of movies at your fingertips.</h2>
      <p>Choose from the latest titles, with new movies added every day.</p>
    </div>
  </div>
</div>

<div id="carousels-container">
  <div class="row">
    <div class="col-xs-12">
      <div id="carousels_render"></div>
    </div>
  </div>
</div>

<div class="feature">
  <div class="container">
    <h1>Available everywhere</h1>
    <p>Start watching on one device, and pick up where you left off on another device.</p>
  </div>
</div>