config/routes.rb
Rails.application.routes.draw do

  resources :subgenres
  resources :movies
  resources :genres

  get 'lookup/genres' => 'lookup#lookup_genres', as: :lookup_genres

  get '/debug' => 'developer_tools#debug'
  get '/sandbox' => 'developer_tools#sandbox'

  get 'pages/about'
  get 'pages/slide_batch' => 'pages#slide_batch'
  get 'admin/movies_index'

  root 'pages#home'
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col-sm-3">
        <h3>Bolt</h3>
        <ul>
          <li>Careers</li>
          <li>Terms</li>
          <li>Help</li>
        </ul>
      </div>
      <div class="col-sm-3">
        <h3>More Bolt</h3>
        <ul>
          <li>Gift Cards</li>
          <li>Trailers</li>
        </ul>
      </div>
      <div class="col-sm-3">
        <h3>News</h3>
        <ul>
          <li>Blog</li>
          <li>Twitter</li>
          <li>YouTube</li>
          <li>Google+</li>
          <li>Facebook</li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar jumbotron-header navbar-fixed-top">
  <div class="container-fluid">

    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">
        <%= image_tag("bolt-network.svg", id: "logo") %>
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">
        <li class="dropdown visible-xs mobile-search">
          <span>Search</span>
          <div class="searchMobile">
            <i class="fa fa-search" id="searchIcon" aria-hidden="true"></i>
            <%= form_tag(movies_path, method: "get", id: "search-form", class: "form-inline", role: "form") do %> 
              <%= text_field_tag(:search, params[:search], class: "form-control search-input-mobile", placeholder: "Search titles") %>
            <% end %>
            <i class="fa fa-times" id="closeIcon-mobile" aria-hidden="true"></i>
          </div>
        </li>
        <li class="dropdown" id="nav-item">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Browse <span class="caret"></span></a>
          <ul class="dropdown-menu" id="browse-menu">
            <% @genres.each do |genre| %>
              <li><%= link_to "#{genre.name}", genre_path(genre) %></li>
            <% end %>
          </ul>
        </li>   
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li class="hidden-xs">
          <button class="searchBox" id="nav-item">
            <i class="fa fa-search" aria-hidden="true"></i><span>Search</span>
          </button>
          <div class="searchWrapper">
            <div class="searchInput">
              <i class="fa fa-search" id="searchIcon" aria-hidden="true"></i>
              <%= form_tag(movies_path, method: "get", id: "search-form", class: "form-inline", role: "form") do %> 
                <%= text_field_tag(:search, params[:search], class: "form-control search-input-large", placeholder: "Search titles") %>
              <% end %>
              <i class="fa fa-times" id="closeIcon" aria-hidden="true"></i>
            </div>
          </div>
        </li>
        <li class="dropdown" id="nav-item">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/admin/movies_index">Movies</a></li>
            <li><a href="/genres">Genres</a></li>
          </ul>
        </li>
        <li id="nav-item">
          <a href="#">Log in</a>
        </li>
        <li class="nav-button">
          <a href="#" class="btn btn-default">Sign up</a>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <title>Bolt Network</title>
  <link href='https://fonts.googleapis.com/css?family=Oxygen:300,400,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://use.fontawesome.com/042562367c.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>

<main>
<%= yield %>
</main>

<%= render 'layouts/footer' %>

</body>
</html>

app/views/layouts/sandbox.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <title>Bolt Network</title>
  <link href='https://fonts.googleapis.com/css?family=Oxygen:300,400,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'sandbox', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'sandbox', 'data-turbolinks-track' => true %>
  <script src="https://use.fontawesome.com/042562367c.js"></script>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller.controller_name %>">

<%= render 'layouts/navbar' %>

<main>
<%= yield %>
</main>

<%= render 'layouts/footer' %>

</body>
</html>